config/routes.rb
Rails.application.routes.draw do
  
  resources :restaurants, only: [:index, :show]
  resources :reviews
  resources :users
  resources :reservations
  resources :locations, only: [:index, :show]
  get '/', to: 'users#home', as: "home"
  get '/contact', to: 'users#contact', as: "contact"
  get '/stats', to: 'users#stats', as: "stats"
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#process_login'
  get '/logout', to: 'sessions#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :reviews
    has_many :reservations
    has_many :restaurants, through: :reviews
    has_many :restaurants, through: :reservations

    validates :first_name, presence: true #capitalization
    validates :last_name, presence: true #capitalization
    validates :birthdate, presence: true #today's year is the limit
    validates :phone_number, presence: true #just numbers, no characters
    validates :email, presence: true #all lowercase, check for a @ symbol

    validates :username, uniqueness: true

    def display_name
        return self.username.capitalize
    end 

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def favorite_restaurants
        highest_rated = 0
        favorite_restaurant = nil
        self.reviews.each do |review|
            if review.stars > highest_rated
                highest_rated = review.stars 
                favorite_restaurant = review.restaurant.name
            end 
        end 
        return favorite_restaurant
    end

    def least_favorite_restaurants
        lowest_rated = 6
        least_favorite_restaurant = nil
        self.reviews.each do |review|
            if review.stars < lowest_rated
                lowest_rated = review.stars 
                least_favorite_restaurant = review.restaurant.name
            end 
        end 
        return least_favorite_restaurant
    end

    def self.longest_review
        longest_length = 0
        longest_review = nil
        self.all.each do |user|
            user.reviews.each do |review|
                if review.content.length > longest_length
                longest_length = review.content.length
                longest_review = review
                end 
            end 
        end 
    return "#{longest_review.restaurant.name}, #{longest_review.content}"
  end 
  

    def self.most_reviews
        most_reviews = 0
        prolific_user = nil
        self.all.each do |user|
            if user.reviews.length > most_reviews
                most_reviews = user.reviews.length
                prolific_user = user
            end
        end
        prolific_user
    end
    
    # def upcoming_reservations
    #     self.reservations.date 
    #     Date.today.strftime
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized
    skip_before_action :authorized, only: [:home, :new, :create, :contact]
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def home
        if logged_in?
            redirect_to users_path
        end
    end 

    def index 
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end 
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.save
            redirect_to user_path(@user)
        else
            render :edit
        end 
    end

    def destroy
        @user.destroy
        redirect_to home_path
    end

    def stats
    end 

    private

    def find_user
        @user = User.find(session[:user_id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :birthdate, :phone_number, :email, :username, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
        <%= message %><br>
    <% end %>
<% end %> 

<div class="userform">

<%= form_for @user do |f| %>

    <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :birthdate %>
        <%= f.date_field :birthdate, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, type: "email", class: "form-control", placeholder: "name@example.com" %>
    </div>

    <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
    </div>
        
    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
    </div>
        
    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

</div>

app/views/users/contact.erb
<h1> Contact Us </h1> 

<h2> Address: 123 Welp Lane, Washington DC, Maryland <br>

 Phone number: 301-992-WELP <br>

 Email: welp.customerservice@welp.com <br>

 Customer service hours:
 Monday-Friday: 9am to 5pm</h2>

app/views/users/edit.erb
<h1> Edit your account </h1>

<%= render partial: 'user_form' %>

app/views/users/home.erb
<h1 id="welcome", class="homewelcome">
Welcome to Welp D.C.!
</h1>

app/views/users/index.erb
<% if session[:user_id] %>
    <h1 class="homewelcome">Welcome back to Welp D.C<br><%= current_user.display_name %>!</h1>
<% end %>

app/views/users/new.erb
<div class="formbackground">
<%= render partial: 'user_form' %>
</div>

app/views/users/show.erb
 
<h1> Your Profile</h1>

<h2> First name:
<%= @user.first_name %><br>
Last name:
<%= @user.last_name %><br>
Birthday:
<%= @user.birthdate %><br>
Phone number:
<%= @user.phone_number %><br>
Email address:
<%= @user.email %><br>

<%= button_to "Delete Account", {:controller => :users,
    :action => 'destroy', :id => current_user.id }, :method => :delete %>
</h2>

app/views/users/stats.erb
<div class= stats>
<h1>Analytics</h1>

<div class="container">
    <div class="row">

    <div class="col-sm">
    <h2>User<br>
        <br>
    Star Welper:
    <p> <%= User.most_reviews.full_name %>

    </p></h2>


    </div> 

    <div class="col-sm">
    <h2>Review<br>
        <br>
    Most recent review:
    
            <p> <%= link_to Review.most_recent_review.content, review_path(Review.most_recent_review) %>
            </p>
    <p>
Longest Review:
  <%= User.longest_review %><br>

   <br> Most Popular: <br>
   Fast Food:
  <%= Restaurant.highest_rated_by_category("Fast Food") %>
   </h2>
    </p>
    </div>  

    <div class="col-sm">
    <h2>Restaurant<br>
        <br>
    Most Popular Restaurant:
    <p> <%= link_to Restaurant.most_stars.name, restaurant_path(Restaurant.most_stars) %>
    </p></h2>
    <br>
    <h2>Most Expensive Restaurant:<br>
    <p> <% Restaurant.most_expensive.each do |restaurant| %>
        <%= link_to restaurant.name, restaurant_path(restaurant) %>
        <% end %></h2>

    </p>
    <br>
    <h2>
    Cheapest Restaurant:<br>
    <p> <% Restaurant.cheapest_restaurants.each do |restaurant| %>
        <%= link_to restaurant.name, restaurant_path(restaurant) %><br>
        <% end %>
    </p></h2>
    </div> 

    </div>
</div>
</div>