config/routes.rb
Rails.application.routes.draw do
  
  resources :restaurants, only: [:index, :show]
  resources :reviews
  resources :users
  resources :reservations
  resources :locations, only: [:index, :show]
  get '/', to: 'users#home', as: "home"
  get '/contact', to: 'users#contact', as: "contact"
  get '/stats', to: 'users#stats', as: "stats"
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#process_login'
  get '/logout', to: 'sessions#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user

    def self.total_reservations
        self.all.count
    end 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authorized
    before_action :find_reservation, only: [:show, :edit, :update, :destroy]

    def index
        @reservations = Reservation.all
    end

    def show
    end

    def new
        @reservation = Reservation.new
    end

    def create
        @reservation = Reservation.new(reservation_params)
        @reservation.user = current_user
        @reservation.save
        if @reservation.save
            redirect_to reservation_path(@reservation)
        else
            render :new
        end 
    end

    def edit
    end

    def update
        @reservation.update(reservation_params)
        if @reservation.save
            redirect_to reservation_path(@reservation)
        else
            render :edit
        end 
    end

    def destroy
        @reservation.destroy
        redirect_to home_path
    end

    private

    def find_reservation
        @reservation = Reservation.find(params[:id])
    end

    def reservation_params
        params.require(:reservation).permit(:date, :time, :guests, :restaurant_id, :user_id)
    end

end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/_reservation_form.erb
<h2>
<%= form_for @reservation do |f| %>
<%= f.label :date %>
<%= f.date_field :date %>
<%= f.label :time %>
<%= f.time_field :time %>
<%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>

<%= f.submit "Submit" %>

<% end %>
</h2>

app/views/reservations/edit.erb
<h1> Edit your reservation </h1>

<%= render partial: 'reservation_form' %>

app/views/reservations/index.erb
<h1> Your reservations: 
   <%= button_to "Create Reservation", new_reservation_path, :method => "get" %>  </h1> 

<% @reservations.each do |reservation| %>
<div class="container">
<div class="card">
        <div class="card-body">
                <h1 class="card-title"> <%= reservation.restaurant.name %> </h1>
                <h3>Number of guests: <%= reservation.guests %></h3>
               <h3>Date: <%= reservation.date %></h3>
               <h3>Time: <%= reservation.time %></h3>
               <%= button_to "Delete Reservation", {:controller => :reservations,
                :action => 'destroy', :id => reservation.id }, :method => :delete %>
        </div>
    </div>
</div>
<% end %>

app/views/reservations/new.erb
<h1> Create a reservation </h1> 

<%= render partial: 'reservation_form' %>

app/views/reservations/show.erb
<h1> Your Reservation:</h1>




<div class="container">
    <div class="card">
        <div class="card-body">
                <h1 class="card-title"> Your Reservation:</h1>
            <p><%= @reservation.restaurant.name %></p>
            <p><%= @reservation.date %></p>
            <p><%= @reservation.time %></p>
        </div>
    </div>
</div>