config/routes.rb
Rails.application.routes.draw do
  
  resources :restaurants, only: [:index, :show]
  resources :reviews
  resources :users
  resources :reservations
  resources :locations, only: [:index, :show]
  get '/', to: 'users#home', as: "home"
  get '/contact', to: 'users#contact', as: "contact"
  get '/stats', to: 'users#stats', as: "stats"
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#process_login'
  get '/logout', to: 'sessions#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
        <div class="container">

                <!-- Call to action -->
                <ul class="list-unstyled list-inline text-center py-2">
                  <li class="list-inline-item">
                    <h5> <%= link_to "Contact us!", contact_path, class:"mb-1" %></h5>
                  </li>
                  <li class="list-inline-item">
                    <h5><%= link_to "Welp Stats!", stats_path, class:"mb-1" %></h5>
                  </li>
                </ul>
                <!-- Call to action -->
            
              </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav id="mycolor" class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="/"><img class="image-logo" src="/assets/logo.png"/></a>
      
        <a class="navbar-brand" image_tag="assets/images/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
              <%= link_to "Restaurants", restaurants_path, class:"nav-link" %>
            </li>
            <li class="nav-item active">
                <li class="nav-item active">
                    <%= link_to "Locations", locations_path, class:"nav-link" %>
                  </li>
                <% if current_user %>
                <li class="nav-item active">
                    <%= link_to "Create Review", new_review_path, class: "nav-link" %>
                  </li>
                <% end %>
              </li>
                <li class="nav-item active">
                    <%= link_to "Reservations", reservations_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item active">
                      <%= link_to "Reviews", reviews_path, class:"nav-link" %>
                    </li>
                  
          </ul>
          <form class="form-inline my-2 my-lg-0">
                <a class="ui item">
                        <% if current_user %>
                      <%= link_to "Log Out", logout_path, class: "nav-link" %>
                      <%= link_to "Profile Page", user_path(current_user), class: "nav-link" %>
                      <% else %>
                      <%= link_to "Create New User", new_user_path, class: "nav-link" %>
                      <%= link_to "Login", login_path, class: "nav-link" %>
                        <% end %>
                    </a>
            <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
          </form>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    
    <link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">
  
   <%= render "layouts/header" %>
   <body>
    <%= yield %>
  </body>
    <%= render 'layouts/footer' %>
  
</html>